language: node_js
node_js:
  - lts/*
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: blog/.vuepress/dist
  github-token: $access_token # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
